package com.esdk.test.orm;
import java.math.BigDecimal;
public class OrderFeedbackExtentMetaData{
  public static final String TABLENAME="OrderFeedbackExtent";
  public static final String PrimaryKey="OrderID";
  public static final int IPrimaryKey=0;
  public static final String[] UniqueIndexFields=new String[]{};
  public static final String OrderID="OrderID";
  public static final String ClientID="ClientID";
  public static final String OrderTypeID="OrderTypeID";
  public static final String OrderNumber="OrderNumber";
  public static final String FeedbackResult="FeedbackResult";
  public static final String CurrentStep="CurrentStep";
  public static final String WarehouseOutFeedbackTime="WarehouseOutFeedbackTime";
  public static final String WarehouseInFeedbackTime="WarehouseInFeedbackTime";
  public static final String FirstCarryFeedbackTime="FirstCarryFeedbackTime";
  public static final String LastCarryFeedbackTime="LastCarryFeedbackTime";
  public static final String FullCarryFeedbackTime="FullCarryFeedbackTime";
  public static final String ArrivedFeedbackTime="ArrivedFeedbackTime";
  public static final String SignFeedbackTime="SignFeedbackTime";
  public static final String FinanceFeedbackTime="FinanceFeedbackTime";
  public static final String IsFeedbackFinish="IsFeedbackFinish";
  public static final String HandleTime="HandleTime";
  public static final String Valid="Valid";
  public static final String ReceiptTime="ReceiptTime";
  public static final String[] FieldNames=new String[]{"OrderID","ClientID","OrderTypeID","OrderNumber","FeedbackResult","CurrentStep","WarehouseOutFeedbackTime","WarehouseInFeedbackTime","FirstCarryFeedbackTime","LastCarryFeedbackTime","FullCarryFeedbackTime","ArrivedFeedbackTime","SignFeedbackTime","FinanceFeedbackTime","IsFeedbackFinish","HandleTime","Valid","ReceiptTime"};
  public static final Class[] FieldTypes=new Class[]{BigDecimal.class,BigDecimal.class,BigDecimal.class,String.class,String.class,String.class,BigDecimal.class,BigDecimal.class,BigDecimal.class,BigDecimal.class,BigDecimal.class,BigDecimal.class,BigDecimal.class,BigDecimal.class,Boolean.class,BigDecimal.class,Boolean.class,BigDecimal.class};
  public static final int IOrderID=0;
  public static final int IClientID=1;
  public static final int IOrderTypeID=2;
  public static final int IOrderNumber=3;
  public static final int IFeedbackResult=4;
  public static final int ICurrentStep=5;
  public static final int IWarehouseOutFeedbackTime=6;
  public static final int IWarehouseInFeedbackTime=7;
  public static final int IFirstCarryFeedbackTime=8;
  public static final int ILastCarryFeedbackTime=9;
  public static final int IFullCarryFeedbackTime=10;
  public static final int IArrivedFeedbackTime=11;
  public static final int ISignFeedbackTime=12;
  public static final int IFinanceFeedbackTime=13;
  public static final int IIsFeedbackFinish=14;
  public static final int IHandleTime=15;
  public static final int IValid=16;
  public static final int IReceiptTime=17;
}
